// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC1DBnUdLZ33c45NvR3yYONmgB8eDZsCA',
    appId: '1:243535250618:web:7a839d4a474b36a1882e83',
    messagingSenderId: '243535250618',
    projectId: 'habitsprout',
    authDomain: 'habitsprout.firebaseapp.com',
    storageBucket: 'habitsprout.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIJsPC3TyhB_XemzZ4bJalTZQuJnMuB20',
    appId: '1:243535250618:android:f48987eef705b189882e83',
    messagingSenderId: '243535250618',
    projectId: 'habitsprout',
    storageBucket: 'habitsprout.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC1DBnUdLZ33c45NvR3yYONmgB8eDZsCA',
    appId: '1:243535250618:web:2f7c054bef230e46882e83',
    messagingSenderId: '243535250618',
    projectId: 'habitsprout',
    authDomain: 'habitsprout.firebaseapp.com',
    storageBucket: 'habitsprout.appspot.com',
  );
}
